# Generated by Django 4.2.5 on 2025-08-13 01:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_type', models.CharField(choices=[('task_prioritization', 'Task Prioritization'), ('context_analysis', 'Context Analysis'), ('deadline_suggestion', 'Deadline Suggestion'), ('task_enhancement', 'Task Enhancement'), ('categorization', 'Categorization')], max_length=30)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField()),
                ('processing_time_ms', models.IntegerField()),
                ('model_used', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contextentry',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority_score', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contextentry',
            name='source',
        ),
        migrations.RemoveField(
            model_name='contextentry',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contextentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='extracted_tasks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='mentioned_deadlines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='source_identifier',
            field=models.CharField(blank=True, help_text='Sender, subject, etc.', max_length=200),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='source_type',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('notes', 'Notes'), ('calendar', 'Calendar'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contextentry',
            name='urgency_indicators',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_enhanced_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_suggested_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority_score',
            field=models.FloatField(default=0.5, help_text='AI-calculated priority score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.CreateModel(
            name='TaskTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_suggested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasktag')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='tasks.task')),
            ],
            options={
                'unique_together': {('task', 'tag')},
            },
        ),
    ]
